### ISSUE TITLE
alignment = 'top_right', does not work

### ISSUE THREAD

**Issue by hajo62** [Conky-for-macOS/default-themes#2]
Not sure, if this is the right place. If not, where to discuss this?
When I modify the alignment (alignment = 'top_left',) to be on the right screen edge, the widgets do not appear or appear in a tiny window size.

**Comment by npyl** [comment]
Hi!!! 
Thanks for reporting this!

Does this happen with every conky config
?

**Comment by hajo62** [comment]
yes. Tried it with default, with the 8 CPU monitor and with my own
worked around with align left and x-offset 1000, but this is not so nice, and does not work when changing the resolution, i.e. by connecting to an external monitor

**Comment by npyl** [comment]
This is interesting.
Can't say i havent noticed similar behaviour on my machine.

**Comment by hajo62** [comment]
Hhm, strange.
I just did modify the TeejeeTech/CPU Panel, line 13 to 
	alignment = 'top_right'
and I do see the strange behavior.
But figured out that adding the following does help:
	minimum_width = 350, minimum_height = 300,

But beside this: Thanks for porting conky to mac ;)

**Comment by npyl** [comment]
You are welcome 😊😊
Thank you for this info

**Comment by npyl** [comment]
Is this an issue for linux-conky too? Do you have easy access to linux so you can check for me? I am only on mac right now 😆

**Comment by abelhavalos** [comment]
> 

this works for me:
conky -atr
